name: Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  linter:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Analysing code with Flake8
        run: |
          tox -e lint

      - name: Type checking code with Mypy
        run: |
          tox -e type
